apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: homeops
spec:
  interval: 10m0s
  dependsOn:
    - name: helm-repos
    - name: infra
    - name: sealed-secrets
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nextcloud
      namespace: nextcloud
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: pihole
      namespace: pihole
    - apiVersion: apps/v1
      kind: Deployment
      name: registry
      namespace: registry
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: unifi
      namespace: unifi
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: velero
      namespace: velero
  sourceRef:
    kind: GitRepository
    name: homeops
  path: ./flux/apps/pinfra
  prune: true
  validation: client
