apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: homeops
spec:
  interval: 10m0s
  dependsOn:
    - name: helm-repos
    - name: infra
    - name: sealed-secrets
    - name: velero
  sourceRef:
    kind: GitRepository
    name: homeops
  path: ./flux/apps/pinfra
  prune: true
