apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: helm-repos
    - name: infra
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/pinfra
  prune: true
  validation: client
