apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra
  namespace: homeops-public
spec:
  interval: 10m0s
  dependsOn:
    - name: helm-repos
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: homeops-public
  path: ./flux/infra/pinfra
  prune: true
  validation: client
