apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: misc
  namespace: homeops
spec:
  interval: 10m0s
  dependsOn:
    - name: infra
  sourceRef:
    kind: GitRepository
    name: homeops
  path: ./flux/misc/pinfra
  prune: true
  validation: client
