apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: homeops
spec:
  interval: 10m0s
  dependsOn:
    - name: helm-repos
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sealed-secrets
      namespace: kube-system
  sourceRef:
    kind: GitRepository
    name: homeops
  path: ./flux/sealed-secrets
  prune: true
  validation: client
