apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: homeops
spec:
  chart:
    spec:
      version: "=2.12.0"
  interval: 10m0s
  dependsOn:
    - name: helm-repos
  sourceRef:
    kind: GitRepository
    name: homeops
  path: ./flux/sealed-secrets
  prune: true
