#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
    echo "usage: $0 <k3s-server> <host>"
    exit 1
fi

K3S_SERVER="$1"
HOST="$2"

k3sup join \
      --host "${HOST}" \
      --user pi \
      --server-host "${K3S_SERVER}"
