#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "usage: $0 <host>"
    exit 1
fi

K3S_SERVER=${K3S_SERVER:-"$1"}

k3sup install \
      --host "${K3S_SERVER}" \
      --user pi \
      --k3s-extra-args '--no-deploy traefik'
