apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: homeops
  interval: 5m
  values:
    resources:
      limits:
        cpu: 100m
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 4Gi
    ingress:
      enabled: true
    persistentVolumeClaim:
      enabled: true
      annotations:
        volumeType: local
        kustomize.toolkit.fluxcd.io/prune: disabled
    serviceDns:
      type: LoadBalancer
      externalTrafficPolicy: Local
    serviceWeb:
      type: ClusterIP
