apiVersion: v1
kind: Service
metadata:
  name: teslamate
  namespace: teslamate
spec:
  selector:
    app.kubernetes.io/name: teslamate
  ports:
  - name: teslamate
    port: 4000
    targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: teslamate
spec:
  selector:
    app.kubernetes.io/name: teslamate
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
