apiVersion: v1
kind: ConfigMap
metadata:
  name: automations
  namespace: home-assistant
data:
  office.yaml: ""
  general.yaml: |
    - alias: "Christmas lights on"
      id: christmas_lights_on
      description: ""
      mode: single
      trigger:
        - platform: time
          at: "18:00:00"
      condition: []
      action:
        - type: turn_on
          device_id: 74a4ba1765b3ce50543f8bf7694aafee
          domain: light
          brightness_pct: 100
          flash: long
    - alias: "Christmas lights off"
      id: christmas_lights_off
      description: ""
      mode: single
      trigger:
        - platform: time
          at: "00:00:00"
      condition: []
      action:
        - type: turn_off
          device_id: 74a4ba1765b3ce50543f8bf7694aafee
          domain: light
