apiVersion: v1
kind: ConfigMap
metadata:
  name: configurations
  namespace: home-assistant
data:
  automations.yaml: |
    - alias: "Christmas lights on"
      id: christmas_lights_on
      description: ""
      mode: single
      trigger:
        - platform: time
          at: "18:00:00"
      condition: []
      action:
        - type: turn_on
          device_id: da3f13e59eb6b70b9fd166e858c661d8
          entity_id: 01a7896cc9711317c3f1dd2951840f8d
          domain: light
          brightness_pct: 100
          flash: long
    - alias: "Christmas lights off"
      id: christmas_lights_off
      description: ""
      mode: single
      trigger:
        - platform: time
          at: "00:00:00"
      condition: []
      action:
        - type: turn_off
          device_id: da3f13e59eb6b70b9fd166e858c661d8
          entity_id: 01a7896cc9711317c3f1dd2951840f8d
          domain: light
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # pinfra specific settings
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
      ip_ban_enabled: false
      login_attempts_threshold: 5

    # mDNS reflector: tell homekit the advertise IP address
    homekit:
      advertise_ip: "10.0.4.31"

    media_player:
      - platform: kef
        host: "10.0.1.37"
        type: LSX
        name: Salón
        maximum_volume: 1
        volume_step: 0.05

    mqtt:
      sensor:
        - name: "Office CO2"
          object_id: office_air_monitor_co2
          device_class: carbon_dioxide
          unit_of_measurement: "ppm"
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ value_json.sensorData.0.co2.value
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 9a0db1bc69a41507a757c5d222d4a845dc244d82
        - name: "Office PM2.5"
          object_id: office_air_monitor_pm25
          device_class: pm25
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ value_json.sensorData.0.pm25.value
              if value_json.type=="17" else this.state }}
          unit_of_measurement: "µg/m³"
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Office Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: b7e9459ef047905d96918d8e247b0c3dd61b7cc8
        - name: "Office PM10"
          object_id: office_air_monitor_pm10
          device_class: pm10
          unit_of_measurement: "µg/m³"
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ value_json.sensorData.0.pm10.value
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Office Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 4beba1f55c9fc38b528353a3eeae9df9db9eae0f
        - name: "Office TVOC"
          object_id: office_air_monitor_tvoc
          device_class: volatile_organic_compounds
          unit_of_measurement: "mg/m³"
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ (value_json.sensorData.0.tvoc.value / 218.77) | round(3)
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Office Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 049dba2512f7e141b094799e308d587b1e199174
        - name: "Office Humidity"
          object_id: office_air_monitor_humidity
          device_class: humidity
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ value_json.sensorData.0.humidity.value|round(2)
              if value_json.type=="17" else this.state }}
          unit_of_measurement: "%"
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Office Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: fca28b722b2d263cdda7906b1f1fda67366c9f42
        - object_id: office_air_monitor_temperature
          name: "Office Temperature"
          device_class: temperature
          unit_of_measurement: "°C"
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ value_json.sensorData.0.temperature.value|round(2)
                if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Office Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: c70b69d6dc1ff5ef3c1e86ecca3e547ae11c3c66
        - name: "Terrace CO2"
          object_id: terrace_air_monitor_co2
          device_class: carbon_dioxide
          unit_of_measurement: "ppm"
          state_topic: "homeassistant/qingping/582D34014261/up"
          value_template: >-
            {{ value_json.sensorData.0.co2.value
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34014261/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34014261"]
            name: "Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 6fabf26f-4d08-4352-8923-df0dace0ce9c
        - name: "Terrace PM2.5"
          object_id: terrace_air_monitor_pm25
          device_class: pm25
          state_topic: "homeassistant/qingping/582D34014261/up"
          value_template: >-
            {{ value_json.sensorData.0.pm25.value
              if value_json.type=="17" else this.state }}
          unit_of_measurement: "µg/m³"
          availability:
            - topic: "homeassistant/qingping/582D34014261/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34014261"]
            name: "Terrace Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 173f1958-7917-4707-8e0b-5e6ab38ba7b9
        - name: "Terrace PM10"
          object_id: terrace_air_monitor_pm10
          device_class: pm10
          unit_of_measurement: "µg/m³"
          state_topic: "homeassistant/qingping/582D34014261/up"
          value_template: >-
            {{ value_json.sensorData.0.pm10.value
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34014261/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34014261"]
            name: "Terrace Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: d190357e-ae23-42e3-a34e-fff7b55a6b46
        - name: "Terrace TVOC"
          object_id: terrace_air_monitor_tvoc
          device_class: volatile_organic_compounds
          unit_of_measurement: "mg/m³"
          state_topic: "homeassistant/qingping/582D34014261/up"
          value_template: >-
            {{ (value_json.sensorData.0.tvoc.value / 218.77) | round(3)
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34014261/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34014261"]
            name: "Terrace Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: a2dba3fa-50cb-4e8f-ae3c-e8910e791276
        - name: "Terrace Humidity"
          object_id: terrace_air_monitor_humidity
          device_class: humidity
          state_topic: "homeassistant/qingping/582D34014261/up"
          value_template: >-
            {{ value_json.sensorData.0.humidity.value|round(2)
              if value_json.type=="17" else this.state }}
          unit_of_measurement: "%"
          availability:
            - topic: "homeassistant/qingping/582D34014261/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34014261"]
            name: "Terrace Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 8651a295-db74-4ac4-9dd8-89ea21c711e1
        - object_id: terrace_air_monitor_temperature
          name: "Terrace Temperature"
          device_class: temperature
          unit_of_measurement: "°C"
          state_topic: "homeassistant/qingping/582D34014261/up"
          value_template: >-
            {{ value_json.sensorData.0.temperature.value|round(2)
                if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34014261/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34014261"]
            name: "Terrace Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 9970aab8-9c0d-4983-848f-0c368dd8b04b
        - name: "Living Room CO2"
          object_id: living_room_air_monitor_co2
          device_class: carbon_dioxide
          unit_of_measurement: "ppm"
          state_topic: "homeassistant/qingping/582D3401491F/up"
          value_template: >-
            {{ value_json.sensorData.0.co2.value
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D3401491F/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D3401491F"]
            name: "Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 6fabf26f-4d08-4352-8923-df0dace0ce9c
        - name: "Living Room PM2.5"
          object_id: living_room_air_monitor_pm25
          device_class: pm25
          state_topic: "homeassistant/qingping/582D3401491F/up"
          value_template: >-
            {{ value_json.sensorData.0.pm25.value
              if value_json.type=="17" else this.state }}
          unit_of_measurement: "µg/m³"
          availability:
            - topic: "homeassistant/qingping/582D3401491F/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D3401491F"]
            name: "Living Room Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 173f1958-7917-4707-8e0b-5e6ab38ba7b9
        - name: "Living Room PM10"
          object_id: living_room_air_monitor_pm10
          device_class: pm10
          unit_of_measurement: "µg/m³"
          state_topic: "homeassistant/qingping/582D3401491F/up"
          value_template: >-
            {{ value_json.sensorData.0.pm10.value
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D3401491F/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D3401491F"]
            name: "Living Room Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: d190357e-ae23-42e3-a34e-fff7b55a6b46
        - name: "Living Room TVOC"
          object_id: living_room_air_monitor_tvoc
          device_class: volatile_organic_compounds
          unit_of_measurement: "mg/m³"
          state_topic: "homeassistant/qingping/582D3401491F/up"
          value_template: >-
            {{ (value_json.sensorData.0.tvoc.value / 218.77) | round(3)
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D3401491F/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D3401491F"]
            name: "Living Room Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: a2dba3fa-50cb-4e8f-ae3c-e8910e791276
        - name: "Living Room Humidity"
          object_id: living_room_air_monitor_humidity
          device_class: humidity
          state_topic: "homeassistant/qingping/582D3401491F/up"
          value_template: >-
            {{ value_json.sensorData.0.humidity.value|round(2)
              if value_json.type=="17" else this.state }}
          unit_of_measurement: "%"
          availability:
            - topic: "homeassistant/qingping/582D3401491F/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D3401491F"]
            name: "Living Room Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 8651a295-db74-4ac4-9dd8-89ea21c711e1
        - object_id: living_room_air_monitor_temperature
          name: "Living Room Temperature"
          device_class: temperature
          unit_of_measurement: "°C"
          state_topic: "homeassistant/qingping/582D3401491F/up"
          value_template: >-
            {{ value_json.sensorData.0.temperature.value|round(2)
                if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D3401491F/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D3401491F"]
            name: "Living Room Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 9970aab8-9c0d-4983-848f-0c368dd8b04b

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
