apiVersion: v1
kind: ConfigMap
metadata:
  name: configurations
  namespace: home-assistant
data:
  automations.yaml: |
    - alias: "Christmas lights on"
      id: christmas_lights_on
      description: ""
      mode: single
      trigger:
        - platform: time
          at: "18:00:00"
      condition: []
      action:
        - type: turn_on
          device_id: da3f13e59eb6b70b9fd166e858c661d8
          entity_id: 01a7896cc9711317c3f1dd2951840f8d
          domain: light
          brightness_pct: 100
          flash: long
    - alias: "Christmas lights off"
      id: christmas_lights_off
      description: ""
      mode: single
      trigger:
        - platform: time
          at: "00:00:00"
      condition: []
      action:
        - type: turn_off
          device_id: da3f13e59eb6b70b9fd166e858c661d8
          entity_id: 01a7896cc9711317c3f1dd2951840f8d
          domain: light
