apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  chart:
    spec:
      version: ">=19.0.34 <20.0.0"
  values:
    cnpg:
      main:
        enabled: false
