apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  chart:
    spec:
      version: "=>6.0.1 <6.1.0"
  values:
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: plex.ereslibre.net
            paths:
              - path: /
                pathType: Prefix
        tls:
        - secretName: plex-ereslibre-net-cert
          hosts:
            - plex.ereslibre.net
