apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  template:
    spec:
      containers:
      - name: registry-ui
        env:
        - name: REGISTRY_TITLE
          value: "registry.ereslibre.net"
