apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  chart:
    spec:
      version: ">=14.0.21 <15.0.0"
  values:
    env:
      TZ: Europe/Madrid
    ingress:
      main:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        ingressClassName: nginx
        tls:
          - hosts:
              - unifi.ereslibre.net
            secretName: unifi-ereslibre-net-cert
        hosts:
          - host: unifi.ereslibre.net
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: unifi
                  port: 8443
