apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      version: "=>1.1.1 <1.2.0"
  values:
    ingress:
      enabled: true
      host: longhorn.ereslibre.net
      tls: true
      tlsSecret: longhorn-ereslibre-net-cert
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
    persistence:
      defaultClass: false
