apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: "=1.5.15"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: homeops
  interval: 5m
