apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      version: "=1.9.1"
  values:
    virtualHost: pihole.ereslibre.net
    DNS1: "10.0.0.1"
    DNS2: "10.0.0.1"
    ingress:
      hosts:
        - pihole.ereslibre.net
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: pihole
            spec:
              template:
                spec:
                  dnsConfig:
                    nameservers:
                      - 127.0.0.1
                      - 10.0.0.1
