apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      version: "=2.23.0"
  values:
    virtualHost: pihole.ereslibre.net
    DNS1: "10.0.1.1"
    DNS2: "10.0.1.1"
    admin:
      existingSecret: admin-password
    ingress:
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - pihole.ereslibre.net
      tls:
        - hosts:
            - pihole.ereslibre.net
          secretName: pihole-ereslibre-net-cert
    persistentVolumeClaim:
      enabled: true
      annotations:
        k8up.io/backup: "true"
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: pihole
            spec:
              template:
                spec:
                  dnsConfig:
                    nameservers:
                      - 127.0.0.1
                      - 10.0.1.1
