apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/pihole
  - backup-sealed-secret.yaml
  - backup-schedule.yaml
  - restic-sealed-secret.yaml
  - sealed-secret.yaml
patchesStrategicMerge:
  - helm-release.yaml
