apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/pihole
  - backup-sealed-secret.yaml
  - backup-schedule.yaml
  - restic-sealed-secret.yaml
  - sealed-secret.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: pihole
        namespace: pihole
      spec:
        chart:
          spec:
            version: "=2.29.1"
        values:
          virtualHost: pihole.ereslibre.net
          DNS1: "10.0.1.1"
          DNS2: "10.0.1.1"
          admin:
            existingSecret: admin-password
          ingress:
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
            hosts:
              - pihole.ereslibre.net
            tls:
              - hosts:
                  - pihole.ereslibre.net
                secretName: pihole-ereslibre-net-cert
          persistentVolumeClaim:
            enabled: true
            annotations:
              k8up.io/backup: "true"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
        postRenderers:
          - kustomize:
              patches:
                - patch: |-
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      name: pihole
                    spec:
                      template:
                        spec:
                          dnsConfig:
                            nameservers:
                              - 127.0.0.1
                              - 10.0.1.1
                  target:
                    kind: Deployment
                    name: pihole
                    namespace: pihole
    target:
      kind: HelmRelease
      name: pihole
      namespace: pihole
