apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8up
  namespace: k8up
spec:
  releaseName: k8up
  chart:
    spec:
      chart: k8up
      sourceRef:
        kind: HelmRepository
        name: k8up
        namespace: homeops
  interval: 5m
