apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - ../../base/external-dns
  - sealed-secret.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: external-dns
        namespace: external-dns
      spec:
        chart:
          spec:
            version: "=6.18.0"
        install:
          remediation:
            retries: -1
          replace: true
        upgrade:
          remediation:
            retries: -1
        values:
          cloudflare:
            secretName: cloudflare-token
            email: ereslibre@gmail.com
            proxied: false
          domainFilters:
            - "ereslibre.net"
          provider: cloudflare
          zoneIdFilters:
            - "758030cd504f990331217b76a738dc95"
    target:
      kind: HelmRelease
      name: external-dns
      namespace: external-dns
