apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgBHARBj7ZpsBFicmflH/JQWyTHPNXDFQodHmBmjuVcM/ditpEps/MDcn/4N6UynTzje3CoeEh0Wlyzir7Y07Gv7aenMba4zFZxDVMAI8dzMJIaSGBM65p5r30uF6WOOmbw1DWwzYQWzN5rfERuTrPTnDm0geWOtKV16Yg2p1P4y1aiim95+H7bPHDOZf0RfEqraPGenaJQI7BSzp+HRyeS2+xToq0zgM1r5I71mEZ/6l/zRIYkzly3XpqwT/FUKemWmgLEnpStmE64ZrjiGW7ku7gix2BOkvLdQ9n+PW0yddsVmgvOlijs3Ugy588xlIXaEFxDzbTRhuKwN6uluo/1Ku9gmNPEV3eiDHaPnVqaMX+QJJZuUIzRAqkzPfHih/2+Aqi7KIPbiyxw9ynfJD9zmJU3fTehwIyxewujel6HWYlK+55zIo6heB5yawJK3Lk6vYdEWydPlLTN4akCHuVWGwPVcZoHrqqFafKxhLmuIaSQgLUvcNiVb7i2vtLU2xgAjMgNVjuig7V4G9FAqkO8ayyJW0TST8HLSofLOAXHptHHftWZWXYw5j21lTDm5T1ua0pZOA5FQpEcXG28RLM+FKOWQ3/zHZoAGgx/BsJPE8oQp4VZXoxf1DTBgNYc0oAIMHJOQ1A9CBfv1jgClMjhqiI5JNp4EGgePVYbdji976D3QNkzu0p7E2E42olpJ3gS72MO3bmQ0AvcLqecrhfXLNb/X0ceCKUV5c0H1pAOa0ntQVM/v
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: external-dns
    type: Opaque
