apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgAMUIoYj5LJ+APGYaGzi1ckf4WUiUGxaP66WJVxTMw/35okzNqXnVTC2Y8Du0ZTCP2gY2IXqSHF0EVBnEcQAYgJ7Cl3qVZxLcusei2wmdje7Axu6N719o+lyL2jbwPnDhESDqGpWxAWeUJcgdcINTsX6Ry7meFIk17OKP7NgbkRZrzVrLQI3ZEdYErsouOweBup0Ks8JBc//6Co5e0XGgTnRliHS62OlpTgjQCXaXfQ4lsepPDsZgvxA6vuJZaMbj9XAdfZAcgiH0CfjvCn46aN3IdkBd59g037NEMK/nU5E8FeNx9VdFOuyhAAHD7ad1Li1Lc17YyoOp/0hPcvECGvMhlZ5wBjuwLae9PMyGwAudhqVHOFVRUIRy2ofvlCdxK8YXo8+U0yXbKJGJxK2aJlfRZ5QrWHUFlyCke0AZZMO7BuKJIkK1CL6o3p4OJmwYMMZwGb3b+FvaS7xVIfMLgiIYeVHnmedS+EqyQkDPkFwmyl75rmgsPj7m/j4L1axrcMo93InWmdApUko70/s8SwK0sJrdT/1ZvWMsIXxEra5+bEDnFGZklHJvnsJILAFlNLHcNwKBJN9KXq9+U5In2fxxypPkKi0dkn6YntnS3YgrvBpYmCrNn+URmkt7yVcdkxZP5MhkRg9OB4SPBHCKe0vINkg97ZrFTBd8FUGBLQu2Uccs249YfpmOguXWdnlYiuNy/TPW6gEDy3oEEOGQMDygDWhm7HnjZHsYElGfZT0KmQa/woDv/Q
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: external-dns
    type: Opaque
