apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgBgwVOc4Boe/E/3K6IXVwll1ykb03HLGzIoW+1ghhyRx3QMcyrnxut/D0dJpSTl+X//IIcpexfCZyvy0DtE2z1sx75PdSawcycKUGLrK3u3oepSKq9ZSCWHHnrjxs4K26ByYRvO8JCD7ucR4hOh/FgNHu31GGoqIa+UtWzFjMWzi3HFybN3mb8L4AjymmG2NAYYs4Rf+/il2Vn8yvD4RpZFV1D2qg9xruQylBYj9YKrWKsE6XCyblE5cTSTdNU1YbihyQtdVDX8UT++W/GZNqWkVXSKrfXtS3B0qm+pONp1wtPta4HKQpLmcQ0BcQ6k/1pVzoDEFuGb2xzd3if5mL4tcKUH2JJhHzxI3KvCPE+v2mE4qYACyQleI0iNnL6s0kPgSi8iNP/u8bE3PiHFYthWk5iOk0bUkHMYl9AyO8xmbSySPd7MsQ4hO7Z8ZLkg37alK+ymm4SZGGPJiw8yfJvh3jlJ2BvUVrn0g3o7LUq+pETkP3VIOrkYoBOc4z/WbzPGgXlA4tf3UROPuDShs/33fMiDAFOzxnye9VL3u6lTCirRQY2LjskSbZBcAz2dK4V8asLylXO7zbGUXGh8hheZxpgnvM1mYO0ub01zGUpYvq14xiesMVqsrUkciziFsSj0QzMbuvxEApRaBEpMvpyPwtGd+RnFjuYI83wk7kJwwagT8ysvrUwBrs0MsH4uwidCBh3pfqa034guIgUuJ4MgO1+XSTfMlivynwnjNbecGKo1GKwT2M78
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: external-dns
    type: Opaque
