{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-token",
    "namespace": "external-dns",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-token",
        "namespace": "external-dns",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "cloudflare_api_key": "AgA3ago2gj7QwSpgf0v0uz0vKH+Yc+A5fPyI5UDbz9+atEKrqWvZqzUhlGmoikJXiDHx9r/PZWl1UrlUPMcgS1HdMtg03rf5hj9YmlUPwbo8zp+jEu1sQGxYvrh02Nl8lgOdrupo4GQxfeTNnQ5WDdHdaxIarZvE1Nz6KtY4doYo4ZfymHQVNztegGZHPYlpoSOOkh/pzzN1tcvrWM/r99M1wEgwlE9nhBkL6ZnNtvO545qByCMIyNahxgTQ3GahdCuXQVYnJ/BRA+FFOYreJmOWWq1KnndA4Hdn84FZG6CgWk+Z9pX+qPKr6V+VSRITiNoUag6sXAcvNQUdwrM0Y3eDDmewXqNtYXRRTdQKjBQEvdjQ6ilMHd77GcbZM4wPvWOe5oXy1mJjRl4ZDLu+LdYVk7Cr1y2irzOPeBR4VA074UIpl9Mw5xCGmuXYl2tUBeDOy2eiQ9uX12SzC2lajqOHK8aTUK+TB4NANpeB2AOLz9e4U2i7FLS/UhJbOnGwifQix242SoXx8j7uoYzHRXSa9Ob1F0mPzStAH8I5Yqxs2/XRD7Qe8mvbL0POA6CpCi1QPdmLmxVoGwWYDCdOiyT1vBUWIxcxbTAiyb5GRSN5KBNAwfLkK7j2FsFKpiy1fbYEzmE1nFBeh4T+YO6QA7yH070AihiemAtY1vQdFiAXXh4QT1ja2uG/nzkj6UPyHg4iSD6D/GyCATHFCt8RfG0rPbrclrK6hc2RdamSfBA+VOD/klwH"
    }
  }
}
