apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiori-data
  namespace: shiori
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
