apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiori-data
  namespace: shiori
  annotations:
    volumeType: local
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
