apiVersion: batch/v1
kind: CronJob
metadata:
  name: upload-synology-ereslibre-net-cert
  namespace: upload-certs
spec:
  schedule: "0 0 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: upload-certs
          containers:
          - name: upload-certs
            image: nixery.dev/shell/kubectl/openssh/shadow
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: ssh-key
              mountPath: "/etc/ssh-key"
            - name: upload-certs
              mountPath: "/tmp/upload-certs"
              readOnly: true
            command: ["/bin/bash", "-c"]
            args: ["/tmp/upload-certs/upload-certs.sh"]
          volumes:
          - name: ssh-key
            secret:
              secretName: upload-certs-ssh-key
              defaultMode: 400
          - name: upload-certs
            configMap:
              name: upload-certs
              defaultMode: 700
          restartPolicy: OnFailure
