apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: unifi
  labels:
    app.kubernetes.io/name: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unifi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unifi
    spec:
      containers:
      - name: unifi
        image: ghcr.io/jacobalberty/unifi-docker:v8.4.59
        env:
        - name: TZ
          value: "Europe/Madrid"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        - name: stun
          containerPort: 3478
          protocol: UDP
        resources:
          requests:
            cpu: "150m"
            memory: "1024Mi"
          limits:
            cpu: "512m"
            memory: "2048Mi"
        volumeMounts:
        - name: data
          mountPath: /unifi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: unifi-data
