apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  releaseName: unifi
  chart:
    spec:
      chart: unifi
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: homeops
  interval: 5m
