apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  releaseName: unifi
  chart:
    spec:
      chart: unifi
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: homeops
  interval: 5m
  values:
    service:
      main:
        ports:
          speedtest:
            type: LoadBalancer
          stun:
            type: LoadBalancer
          syslog:
            type: LoadBalancer
          discovery:
            type: LoadBalancer
      persistence:
        data:
          enabled: true
          accessMode: ReadWriteOnce
          size: 10Gi
