apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  releaseName: unifi
  chart:
    spec:
      chart: unifi
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: homeops
  interval: 5m
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: unifi
            spec:
              template:
                spec:
                  containers:
                    - name: unifi
                      startupProbe:
                        httpGet:
                          path: /status
                          port: https-gui
                          scheme: HTTPS
                        failureThreshold: 30
                        periodSeconds: 10