apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unifi
resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml
  - service-device-raw.yaml
