apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      version: "=6.0.0"
  install:
    remediation:
      retries: -1
    replace: true
  upgrade:
    remediation:
      retries: -1
  values:
    configuration:
      provider: aws
      backupStorageLocation:
      - name: aws
        provider: velero.io/aws
         bucket: pinfra-backup
         config:
           region: eu-west-1
      volumeSnapshotLocation:
      - name: aws-default
        provider: velero.io/aws
        config:
          region: eu-west-1
      schedules:
        weekly-backup:
          schedule: "0 0 * * 0"
          template:
            includeClusterResources: true
            includedNamespaces:
            - '*'
            includedResources:
            - '*'
            storageLocation: aws
            snapshotVolumes: true
            ttl: 240h
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.9.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
