apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      version: "=>2.22.0 <2.23.0"
  values:
    configuration:
      provider: aws
      backupStorageLocation:
        bucket: pinfra-backup
      volumeSnapshotLocation:
        name: aws-default
        config:
          region: eu-west-1
    credentials:
      useSecret: true
      existingSecret: aws-credentials
    upgradeCRDs: false
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.2.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins