apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      version: "=>2.22.0 <2.23.0"
  values:
    configuration:
      provider: aws
      backupStorageLocation:
        bucket: pinfra-backup
      volumeSnapshotLocation:
        name: aws-default
	config:
	  region: eu-west-1
    credentials:
      useSecret: true
      existingSecret: aws-credentials