apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - ../../base/velero
  - sealed-secret.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: velero
        namespace: velero
      spec:
        chart:
          spec:
            version: "=6.0.0"
        install:
          remediation:
            retries: -1
          replace: true
        upgrade:
          remediation:
            retries: -1
        values:
          image:
            tag: v1.13.1
          credentials:
            existingSecret: credentials
          snapshotsEnabled: false
          configuration:
            backupStorageLocation:
            - provider: aws
              bucket: pinfra-backup
              config:
                region: eu-west-1
          initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
          schedules:
            backup:
              disabled: false
              schedule: "0 0 * * 1"
              useOwnerReferencesInBackup: false
              template:
                ttl: "240h"
                storageLocation: default
    target:
      kind: HelmRelease
      name: velero
      namespace: velero
