{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "credentials",
    "namespace": "velero",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "credentials",
        "namespace": "velero",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloud": "AgCOfXba8PpV39dXBEFtKa1G8HIn8uK1AZksm4JTekBenh4UlhyPTO7VNcLQBgJZgaXIXOTjlkz2PStigTKPJL3oQLYY0X9ejEHb0WyiURXdhXr58SBduOCDUHm0vdZDcCLnnVeZ6cN7zc1Q+WvhIZW8JOS1YjlQBd/oPmgYIjBunO6IOA1Gn2d/WREeghBWq6T924+WBixATAH5tts+fJVK4K7t22wS7mYkKuXjeJ0SquImiDJJiF7/vbi8UlTz4ik/0Vk0MUqT2tGeN6Fr9Y/30+ncSo1yVQU48FGKypjkiov+SY/O3VkGZreNh9kanIP2NncanwXWOzUq6J6fNgx77NLPmF6GyLZDq/cUa13nDoDE0t3WBJs9WPQ/6j+4hkdbB47iClrOaePTw51xgRMahTQDjVLmjZOkkU45ovGJyZInFhe87TSy2zDTzAd3W1auCoy0pKXHKN/FQvyrXh2V7mE31nEdp4psXMSL0skCeFTEdMoOnCS+Laf6VNsKvht+nvqvGOaigFH+G25GBpnHp9bck0KSKcV2Ebcsvo/IAttoXsa1WwLXFng9j7s544l8ZEy7JpU+EbvfhGH/izBJVX9eZ9R6/NZptbNieeZUzfQCyv8GYBZet7EczHRsYdJ0RmzU90UZ6RjTDn+HYFZhzBtQ2UeZOD/5l07Y4dNPZRVK/0uQ48c4IUIMW4aPdmZTDItkF4+hmqJ+YlwPejRalCLbEJlipT7yDrAakD7qJOtT7SnMOQ9f1I42iZrOpUVxuabfMWJodziK3PfFtmx7pITinELM2WymI8isO40ZXAAwmh9k96vgRw/YzlQMPCMvQEEjKfrKEVxP9ENrWLg="
    }
  }
}
