---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backup-credentials
  namespace: mosquitto
spec:
  encryptedData:
    access-key-id: AgAuuQmLl7uogUGU44x/8lUip0G/Q1nVjnNF8Rdus7QOknlsMl/nXLWbvbyBGFbxMpVxXIapurwA77yYxFn8tMHTmCJP48t6pUBSM0lMFUwb5Qcixwx5A4CiZ1Ke/UsbaYPQkpqoenEMogzPNKA0PESHEM/EPfVtIGmX3BT0JW86Euhw0Ii4NMQZIjLV/Lhstwkxrzgs27yhEESjF1oYiNJuEPXZANIYj/ACOCGd2nI0uyK0K/DYjoviGDCn39oOvo3jsWCKPnqFOhCO7otq3IRbsG3Wn8VKoD4ryqFa6bQrJpjaWWIC3Y2jViPtIFiEsqe85eX52Dab2We5M5KNF5Ap0eytLnsOaeAQvgc8Z13S33VsxQfGybvtkIE8W9AOpVTlvA9q9kp9jjsnToYt/FUYflGVCcZIRbdxazpYWtkrb/AZ6T8WVEXKZj5f8VSxAI5bdUalp1b5XF7NX2TAz/C3uybhieFYLZEpOpML6/+2D9DlrgFIXlBXRf4lqS4Lv/IH6x3RM41Mk3fdbyUsiXWCKwqmyPaXCNsQCgTtdFSgJKRW55TG/RbwfYKOmGHNVa7p6kBu52DtZQ88u7q0RhAOuGEBOotAwDtX/sUqP+krT+l7yFOi0FmHfI5Eu3k1Mjv/qH/D3e3Rwuj+qLAM4nr0g9tUGNQwQAv4H4pf4e1klx8lBSvq7WUjtWgo4LqqJhdGWYnoDZjVoskP7kr4KKIBkm3ziA==
    secret-access-key: AgATE35wvAQ9XRLmPGXNW+UZc/IKxSv1CdVRouI5FBzBYys9+hDAxfLe5pkq047rwV4ODLalMQKX2BiTkFpNgyFI2SgJTyQ9/5ubhQt/CyKe/RpayV0lHzx380m91HCEkNNWFkew6uae04u4qcXgW4EEMkdbPEMkJ1kciqWeMtumwJOQ8OOb3b39kZJCjhN2y5BMCjOaERuJVwFDKmkCG95UDBh/FIBxH3nWP1ssMENlNcK7QnxONV0u9Xy0zZCdHAk502HiUv2DJbY6jstcZCOQCIhFufL57xQA7eONdouZ/bMuOuGHBMYqiWxes+zwtTQkVCW63uvBVPVlbPxaGI6OGq3g7KyG5EnGxZNgqI0kCfZFZjGqoAGBoTsNX8c3oDFyFyDeNma4UQOWJDlR3PpIXPKDaheWcbPy2s0OLAMFzh5mi5eh3RejzYL2C+VWrpOZRO++UaHbu/ITfte045lhPRYzIYgQNW/zrXtX027U6kLSTWoWU3bZ+ZeCkEADh1HboPPalU9Srz5nrrSwjVjM3G7T+e941nkfFJciTkobqNBVtb+b6ExLzpgLPSsTQAo9Nk3xYVDaUKgOYGcbekrRPWJrBcOSCIWgEau5Qd6LqilfNX7UU9uktXPBKX1eIQaFgznGoUFSE9HmX7WokPi04oCah3VTgCZjPqvXmdliE4RstmTTFy05v6ZzrO6Ru6AUoBlk4G/BFF0VGWFECINMpYFAKx/fwziUmiJT8Lmwb1OzXtr/4wRI
  template:
    metadata:
      creationTimestamp: null
      name: backup-credentials
      namespace: mosquitto
    type: Opaque
