apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hulk-ipmi-ereslibre-net
  namespace: global-certs
spec:
  secretName: hulk-ipmi-ereslibre-net
  dnsNames:
  - hulk-ipmi.ereslibre.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
