---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-synology-ereslibre-net
  namespace: global-certs
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["synology-ereslibre-net"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-synology-ereslibre-net
  namespace: global-certs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-synology-ereslibre-net
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: upload-certs
  namespace: upload-certs
