apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: synology-ereslibre-net
  namespace: global-certs
spec:
  secretName: synology-ereslibre-net
  dnsNames:
  - synology.ereslibre.net
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
