apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: homeops
  interval: 5m
  install:
    remediation:
      retries: 0
  values:
    defaultSettings:
      systemManagedComponentsNodeSelector: "kubernetes.io/arch:arm64"
    longhornManager:
      nodeSelector:
        kubernetes.io/arch: arm64
    longhornDriver:
      nodeSelector:
        kubernetes.io/arch: arm64
    longhornUI:
      nodeSelector:
        kubernetes.io/arch: arm64
