---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homeops
  namespace: homeops
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: homeops
  url: ssh://git@github.com/ereslibre/homeops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homeops
  namespace: homeops
spec:
  interval: 10m0s
  path: ./flux/clusters/pinfra
  prune: true
  sourceRef:
    kind: GitRepository
    name: homeops
