apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-yaml
data:
  configuration.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
      ip_ban_enabled: false
      login_attempts_threshold: 5
