apiVersion: v1
kind: ConfigMap
metadata:
  name: configurations
data:
  automations.yaml: ""
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # pinfra specific settings
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
      ip_ban_enabled: false
      login_attempts_threshold: 5

    # mDNS reflector: tell homekit the advertise IP address
    homekit:
      advertise_ip: "10.0.4.31"

    media_player:
      - platform: kef
        host: "10.0.1.37"
        type: LSX

    mqtt:
      sensor:
        - name: "CO2"
          object_id: air_monitor_co2
          device_class: carbon_dioxide
          unit_of_measurement: "ppm"
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ value_json.sensorData.0.co2.value
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 9a0db1bc69a41507a757c5d222d4a845dc244d82
        - name: "PM2.5"
          object_id: air_monitor_pm25
          device_class: pm25
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ value_json.sensorData.0.pm25.value
              if value_json.type=="17" else this.state }}
          unit_of_measurement: "µg/m³"
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: b7e9459ef047905d96918d8e247b0c3dd61b7cc8
        - name: "PM10"
          object_id: air_monitor_pm10
          device_class: pm10
          unit_of_measurement: "µg/m³"
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ value_json.sensorData.0.pm10.value
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 4beba1f55c9fc38b528353a3eeae9df9db9eae0f
        - name: "TVOC"
          object_id: air_monitor_tvoc
          device_class: volatile_organic_compounds
          unit_of_measurement: "mg/m³"
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ (value_json.sensorData.0.tvoc.value / 218.77) | round(3)
              if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: 049dba2512f7e141b094799e308d587b1e199174
        - name: "Humidity"
          object_id: air_monitor_humidity
          device_class: humidity
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ value_json.sensorData.0.humidity.value|round(2)
              if value_json.type=="17" else this.state }}
          unit_of_measurement: "%"
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: fca28b722b2d263cdda7906b1f1fda67366c9f42
        - object_id: air_monitor_temperature
          name: "Temperature"
          device_class: temperature
          unit_of_measurement: "°C"
          state_topic: "homeassistant/qingping/582D34701BA9/up"
          value_template: >-
            {{ value_json.sensorData.0.temperature.value|round(2)
                if value_json.type=="17" else this.state }}
          availability:
            - topic: "homeassistant/qingping/582D34701BA9/up"
              payload_available: "true"
              payload_not_available: "false"
              value_template: >-
                {{ "true" if value_json else "false" }}
          device:
            identifiers: ["582D34701BA9"]
            name: "Air monitor"
            model: "CGS1"
            manufacturer: "qingping"
          unique_id: c70b69d6dc1ff5ef3c1e86ecca3e547ae11c3c66

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
  scenes.yaml: ""
  scripts.yaml: ""
