apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-yaml
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # pinfra specific settings
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
      ip_ban_enabled: false
      login_attempts_threshold: 5

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
