apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: home-assistant
  name: home-assistant
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
    spec:
      containers:
      - name: home-assistant-app
        image: ghcr.io/home-assistant/home-assistant:2025.9
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: null
        envFrom:
          - configMapRef:
              name: home-assistant-config
        ports:
          - name: http
            containerPort: 8123
            protocol: TCP
          - name: coiot
            containerPort: 5683
            protocol: UDP
        resources: {}
        livenessProbe:
          tcpSocket:
            port: 8123
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8123
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 8123
          initialDelaySeconds: 0
          failureThreshold: 30
          timeoutSeconds: 1
          periodSeconds: 5
        volumeMounts:
          - name: config-root
            mountPath: /config
          - name: configurations
            mountPath: /config/configuration.yaml
            subPath: configuration.yaml
          - name: configurations
            mountPath: /config/scenes.yaml
            subPath: scenes.yaml
          - name: configurations
            mountPath: /config/scripts.yaml
            subPath: scripts.yaml
      restartPolicy: Always
      volumes:
        - name: config-root
          persistentVolumeClaim:
            claimName: home-assistant-config-root
        - name: configurations
          configMap:
            name: configurations
            items:
            - key: configuration.yaml
              path: configuration.yaml
            - key: scenes.yaml
              path: scenes.yaml
            - key: scripts.yaml
              path: scripts.yaml
