apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: homeops
  interval: 5m
