apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - namespace.yaml
  - configurations.yaml
  - automations.yaml
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml
configMapGenerator:
- name: home-assistant-config
  literals:
  - TZ="Europe/Madrid"
