apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-root
  namespace: home-assistant
  annotations:
    volumeType: local
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
