apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-root
  namespace: home-assistant
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
