apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  selector:
    app.kubernetes.io/name: home-assistant
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: http
    protocol: TCP
    name: http
  - port: 5683
    targetPort: coiot
    protocol: UDP
    name: coiot
