apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: mosquitto
  annotations:
    volumeType: local
    kustomize.toolkit.fluxcd.io/prune: disabled
    k8up.io/backup: "true"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
