apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBRnZAFE0mmy2regbtjWWtcKjYpAKczbUSH+lD1fqDmU4lqrR9FaqQaYdmRhpTUnKMf+rqoTQwJOsGbt9SmEAiEJAT/+5sTPs3+82FucCfTLtjEoWAdRDnKVN54bEcgmpGUXGUWxp633aBQP3LVbe3YehE8dd59nd3z8oYMx9nc8/2jglIV3TBt5jZwj9D+UsQeSNiv3mTfJW9grqzAiA0O7mu2rYR75XL2VWre259JvKX7qcZoNE8/sgaA5C31J7O4Gtm12eWm4SofWJUERsjZVibhBYUi5kNRFZgH8KS8UIWCE10eQUfdr2gBiYB/1OoNDeA37jB7ld5XR22mWsfZIW64CSypHAWM+jhNUgkcQaDTYmGz58EokVDL2+qpKBbi5zqolDfs+dW6JHsddfGB1LiCaPkjnTjUf44J2DojCRCSDC9m7f4ktpKhLldDotJ31pmOILSj+UjZHdyxVfimJN9MMnjweyPFFODLQR7VQ6S4zLtIe6rlbXZQDAgcEV0Xxz6YId2EF3BO61p3v+7PtBkn5vgdadpXPMC7b4bYxcN7hcKPSzZg6iA9BKRf3QveWDUf778H4LZKHDQpDZlytTVPjsgO94fOZaoDgxiEhM21XolBmCG/pAF58IwQ+vMkd9P5N9+DmCSFy58fpkIaqUhXsZrLhpkAETTWkw1Dj/I+vG3VFoLRFXcC+VmAbWrnzC+2ViI6rwqsazhG3RNdUp0urBWqp0EfMmB5/LlcPmACjSCn2fjf
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
    type: Opaque
