apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: homeops-public
spec:
  interval: 5m
  url: https://bitnami-labs.github.io/sealed-secrets
