 apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/k8up
  - sealed-secret.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: k8up
        namespace: k8up
      spec:
        chart:
          spec:
            version: "=4.5.0"
    target:
      kind: HelmRelease
      name: k8up
      namespace: k8up
