apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backup-credentials
  namespace: shiori
spec:
  encryptedData:
    access-key-id: AgCSjv9pT9qMjiME1vByN/RzM/luH7C+IjLeQlMp2yNN9DN/qRBng/VdtJbZYW9uH/HR/6IJeBFQTO2722E4PqxxHo+Mckfpk4IoI9Hw/dxPXoCrdeI79GJ2JhODP1cXFeJ94kl43PEDdq7LACTo1WpbkZlIFnmgf54+k9bxgGMNAaDYTJis7z4zXyI4l/EoB/AG2ovEwG1fzo9Zjfm8xTq6RuCJgv83ytyP67U2FtibxGnLIp17GQuHxBLOdHo+atPxn5EW+/mmGbj9xQaZtQCC86bb7bNnJCrSvD6tEaStmzUeExeKpqsxP2cLs4qpz4jN7f2GuGbX4c5Ahp2HLAnRetQ4xKJ5xWkVZe+Wl1vmS0RGnpy2PNVPPcxPmGqO8m6oH/C1CQshL2PK4HIHU2t3rmxbzFx5Jm3zx38Tdv2GezJCsvJfA1wIeDW9oX9xgX2POLxIYMXsHsgfzLZ3N+IcobiOxJ9kFpMnexmg1PeJvWWHRNQ+Hfeq46wd8UODAx07VDCZn7ffZQeFaQub2q9Mhrb+Ol71ResvU4JWkY+kvVj09ZedGB0msbuv6RFQ+I9zUrVjyO80QracBpWfY2No7YQeiImN+JMQfwIKfqaExugptVZNi5LU7cybfV3sM/MA0rgGjfpHU3qmiVlB4H05tb7QdDoVRKePg4okNFh48ZIZeHk2cStnBjoioDhoDt8Vx9MxRX6PtfSdFh1NVZr69RFYCw==
    secret-access-key: AgAbF9q1ycsYaKKaA/2f/9X/PkZRt01PP07aOvh03JTYSfaLOFS/+hUc/D11qSRfub5P3pyuKbutCCLzZRBNQO+bkyLPbsJ9KSVTv/URbKwVi1GQFPBIr52Kae7t8426HtenMOody5/V9aUlhu1/0zgByvK7qYm4IaIaUoCZ3SXXdBsmYGVBW4oLsj1Cx0SNfZZK/MmmLCNoZOMcI0ubSe9X+cqA8wsnKq8gfV6d4XzhekQz+TAq+dei9CyqhZkUAo3wgHAMlpIlNWKl4hvYxAUgXdV94SjDkBWBAlabhEradqPrg/LRm9CnQCzQ+Z92l3MpW3ax0dRtGOjVmeS7k44+9quw1l/+cNtTP/o+yTFoXewBQSLXZpL/jZmEv/iOA1/urrJDefF81oWcDTYFLsnrbIpQ93D9r9ICO/ctD/xh1CPxT9qx0pg/EwuFLb/IodnbqpnwhYJtEau+DdvGOZ0rx1QDCEkFTh7hqFZHXWsCg11wLgGujLpNVe9gFrIJChEdNtqY6hGWJ+KONl93sIil24F2D8O0xtisedOqzolZ/ix4zc6+8EfpAucAJsOFc4cHNdmji+nqGou5E7B7pBqiQC/jssDFsENqkxVo1NmGki8HRPf9i3W5V5n77A05Xp7V1cwf9P5wWz3vS61Aqw0WkYRd62ps3W7Njfyxou94fLlXBAmGg+uF/At+kVdTl3VfzHeSLhGt2rtdZh9SnrouW9nVzkeVv8af7wBQDC3TUSBBpQfASrYT
  template:
    metadata:
      creationTimestamp: null
      name: backup-credentials
      namespace: shiori
    type: Opaque
