apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: shiori
  namespace: shiori
spec:
  chart:
    spec:
      version: ">=13.0.0 <14.0.0"
  values:
    ingress:
      main:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
