apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/shiori
  - backup-sealed-secret.yaml
  - backup-schedule.yaml
  - restic-sealed-secret.yaml
patches:
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: shiori
        namespace: shiori
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
      spec:
        rules:
        - host: shiori.ereslibre.net
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: shiori
                  port:
                    name: shiori
        tls:
        - hosts:
          - shiori.ereslibre.net
          secretName: shiori-ereslibre-net-cert
    target:
      kind: Ingress
      name: shiori
      namespace: shiori
