apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/shiori
  - backup-sealed-secret.yaml
  - backup-schedule.yaml
  - restic-sealed-secret.yaml
patchesStrategicMerge:
  - ingress.yaml
