apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: restic-credentials
  namespace: shiori
spec:
  encryptedData:
    password: AgCWX/fcwM5gWP/9ddRcBoPVDCfTfPY21TVwmC6A2YdPh2vjdaVDN513igAL9spS5hBGra1EQNsxJOqFKjAPYNUSToxsvN6IMmmOrpXk3b+dFm3Os2Ksa8MT4gL2Y52LSJ2SzDQvAi6+S0Adytw4kUv4hBOLv1HZLpmwUetDpn/SrcSNTPGiYDuuXDpgwqc3ZIueiizIeBPV06agox3ouYvvy1kHFyHLMTjSVF6GM73hAsz9pFBjkt7xs8zUxp36oD6jth+wfHtx4OvdGdQOFrk3kCOY2SqNEkFTrvS15MbP4bvuJ9Bg3TGPpSnePlMeFo6cjI7qIwJlFp76fNa+9K6NPkUg/4lOAm7hV11t0asJnREtkAfveNSRdSYPNV5icfeLygQmMouF2zVJGN3/mf8VS53iDxiftzDLtTO6iSs1gNg9cDsEvOUKwj5EZ+SoGVvjMRpiwFogS6JD6N5gcMtZJ9v/kK8DsJMK/4p6qeil8i7MqW6VHd6hBRMOpe/6mtabdOjW0PFDPi/lN37kNVKEL94TBmwgU+eeZD3ZvWRZdFeXFHOLpBtfIqfhhqLt+XOX4Zbl3pDnYlqz8362myUkQefw27fFit6fxjGiPHYONz4P7xpVytpRwrsGSHJLdc0J0/xGFylj56W8YPiuzCisixO+Loh7ELrvdr644r8Wv5lIr9bvthdaqueAEt4pYICBm+BMn/DwXW07
  template:
    metadata:
      creationTimestamp: null
      name: restic-credentials
      namespace: shiori
    type: Opaque
