apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      version: ">=4.10.0 <4.11.0"
  values:
    controller:
      extraArgs:
        tcp:
          "8883": "mosquitto/mosquitto:8883"
        tcp-services-configmap: "$(POD_NAMESPACE)/tcp-services"
