apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      version: ">=4.10.0 <4.11.0"
  values:
    ports:
      mqtts: 8883
    targetPorts:
      mqtts: 8883
    controller:
      extraArgs:
        tcp-services-configmap: "$(POD_NAMESPACE)/tcp-services"
