apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/ingress-nginx
  - tcp-services.yaml
  - udp-services.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: ingress-nginx
        namespace: ingress-nginx
      spec:
        chart:
          spec:
            version: ">=4.10.0 <4.11.0"
        values:
          controller:
            extraArgs:
              tcp-services-configmap: "$(POD_NAMESPACE)/tcp-services"
              udp-services-configmap: "$(POD_NAMESPACE)/udp-services"
          tcp:
            "8883": "mosquitto/mosquitto-mqtt:8883"
          udp:
            "5683": "home-assistant/shelly-coiot:5683"
    target:
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
